### ISSUE TITLE
Version not available

### ISSUE THREAD

**Issue by m-grem** [kiwimato/invoiceninja-v5-unraid#6]
![Screenshot 2023-01-18 003120](https://user-images.githubusercontent.com/122980983/213162822-90892012-c517-4016-9774-2ccabebd0fd6.png)

The version hasn't been available for about a week. Do you have any idea?
Thanks!!

**Comment by kiwimato** [comment]
That is very interesting, I just checked Dockerhub and the image exists, no obvious issues.
I get the same message in UnRAID but don't know why. Also I did not change anything recently.

Also trying to pull the image just works:
```
[mihai@manticore ~]$ docker pull maihai/invoiceninja_v5:latest
latest: Pulling from maihai/invoiceninja_v5
9621f1afde84: Pulling fs layer 
442a61c63cee: Pulling fs layer 
40ecb9ad4887: Pull complete 
6fa18066724a: Pull complete 
d76918b60bac: Pull complete 
b37f63e25603: Pull complete 
cd064d614b94: Pull complete 
55ee48062424: Pull complete 
8698409c88cd: Pull complete 
c91a581b5c6c: Pull complete 
662b70e0ec95: Pull complete 
e841c80d94b2: Pull complete 
cc8285868174: Pull complete 
0722b7fa8fe9: Pull complete 
0edce17a7484: Downloading [==========>                                        ]   31.2MB/153.8MB
8772c962fbdd: Download complete 
db9238aad2f1: Download complete 
3023afad9813: Downloading [=============================================>     ]  40.45MB/43.97MB
4f4fb700ef54: Download complete 
226242f7a88b: Downloading [==============>                                    ]  36.03MB/125.3MB
15c2a2f9e608: Waiting 
6795101d8816: Waiting 
```

**Comment by m-grem** [comment]
This is interesting. If I delete the application and install it again with "Previous Apps", I get the current version but it shows again: Version not available. 
I set up a new test system to check how ninja works in a new installation. The result is the same.

**Comment by kiwimato** [comment]
hmm, looks more like a UnRAID bug than invoiceninja. 
I installed a new app just to check:
![image](https://user-images.githubusercontent.com/56123381/214040374-cef77921-e503-4056-b4d2-3bbe2d92f216.png)

Then, I clicked Check for updates, and this one also appeared as "not available" even though it wasn't like that before:
![image](https://user-images.githubusercontent.com/56123381/214040502-9e7929ef-6c4f-4c8a-8a05-d94224f94cae.png)

Hitting Check for updates again made it available again, but not for invoiceninja unfortunately. 
![image](https://user-images.githubusercontent.com/56123381/214041439-336a3160-5e85-4a05-9a77-5e730b7fedcd.png)


Could it be because of Dockerhub pull image limits?
I see other people complaing about a similar issue: https://forums.unraid.net/topic/126187-docker-version-not-available-broken-link/

**Comment by kiwimato** [comment]
@m-grem I looked into it today again, and it seems to be a [UnRAID issue](https://forums.unraid.net/topic/132686-docker-updateversion-not-available/)
A solution in my case was to install "Docker update patch" plugin from Apps tab as one of the users suggested, click "Check for updates" again in Docker tab and then "not available" should disappear.
